server:
  port: 8080
  allowOrigins:
    - http://localhost:3000
    - http://example.com
  bodyLimit: 1048576  
  timeout: 30s # Seconds
  jwt_secret_key: "my-secure-secret-key"
 

database:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  dbname: postgres
  sslmode: disable
  schema: public

